### ISSUE TITLE
Deserialize creating the new vector

### ISSUE THREAD

**Issue by FaustinoMalena** [cisc3130/3-tree#3]
So based on an earlier conversation, im wondering that after you make a new vector to hold the children of a given node. Say:
std::vector <tnode*> v;
How would this vector get accessed by a node if it cant point to it?
Unless all we do is dump the nodes children from vector v into vector children.
and dont we need to allocate new memory for both vectors?
I need more clarification.
@rivlev

**Comment by rivlev** [comment]
Each node has a list of children as a data member.
To add a child to a node, insert it into its list of children.

**Comment by FaustinoMalena** [comment]
So we place the limit on how many children is entered ?
