### ISSUE TITLE
push_back word from line to a vector

### ISSUE THREAD

**Issue by Brendafried** [cisc3130/3-tree#4]
When I try to read in from the file a line, and push it to a vector, the entire line becomes one element in the vector. I'm having trouble separating the line so that each word in the line is a different element in the vector. How can I go about this?
@rivlev

**Comment by rivlev** [comment]
There are several solutions discussed [here](https://stackoverflow.com/questions/236129/the-most-elegant-way-to-iterate-the-words-of-a-string?rq=1)
