### ISSUE TITLE
Error after fully implementing Deserialize and Recursive operator equals

### ISSUE THREAD

**Issue by FaustinoMalena** [cisc3130/3-tree#6]
Hello Professor I am receiving this error from travis upon fully implementing deserialize, serialize and operator equals accompanied by recursive helper functions and two outfiles get created

Error:

_________________________________________________Food_________________________________________________
_______________________________Plant_______________________________ ______________Animal______________
_____Roots_____ ____Leaves____ _______________Fruits_______________ ____Fish____ _Mammals_ ___Birds___
Potatoes Carrots Lettuce Cabbage _____Apples_____ Pears Plums Oranges _Salmon_ Tuna Beef Lamb Chicken Duck
_______________ ______________ GrannySmith Gala _____ _____ _______ Wild Farm ____ _________ ___________
__________9__________
__________6__________
__5__ ______4______ 2
10 7 1 _____3_____ 8 _
_____ 11 12 13 14 _ _
/home/travis/.travis/job_stages: line 57:  4477 Killed                  ./a.out

What could this mean, and what can be done to remedy this error  if the first tree food tree clearly passes the recursive equality test and goes through deserialize without incident but int tree does.

I believe my most recent version of my code  needs review.

@rivlev

**Comment by rivlev** [comment]
I don't see this error in Travis; have you fixed it?

**Comment by FaustinoMalena** [comment]
I did'nt make any last minute adjustments recently no, does an error appear for you or is it just me
