### ISSUE TITLE
operator== access rhs children

### ISSUE THREAD

**Issue by Brendafried** [cisc3130/3-tree#7]
for the operator== function
when I recurse and call the function again:  operator==(rhs.root->children[i])
I get this error.
`error: reference to type 'const NTree<std::__1::basic_string<char> >' could not bind to an lvalue of type 'value_type' (aka 'NTree<std::__1::basic_string<char> >::tnode *')`

Is this the correct way to access rhs children? 
@rivlev

**Comment by FaustinoMalena** [comment]
okay so root of rhs is rhs.root

**Comment by rivlev** [comment]
The operator== expects an NTree. ```rhs.root->children[i]``` is a NTree::tnode*. You need to create a recursive helper function that takes an NTree::tnode*

**Comment by Brendafried** [comment]
thank you, that worked!
