### ISSUE TITLE
[Error] invalid user-defined conversion

### ISSUE THREAD

**Issue by fayrouz-mikhael** [cisc3130/3-tree#8]
I am getting this error in 

**C:\Users\User\Documents\Ntree.h	[Error] invalid user-defined conversion from 'int' to 'const string& {aka const std::basic_string<char>&}' [-fpermissive]**

in ::
rq.push(std::to_string(nd->data));

thank you.
@rivlev

**Comment by FaustinoMalena** [comment]
remove to_string

**Comment by Gallald** [comment]
I'm getting the same problem, and removing to_string doesn't change anything with that, @FaustinoMalena

**Comment by Gallald** [comment]
I just ended up downloading DevC++, changed the compiler option to C++11, and after that, it gave me an error saying "std::cout is not a member of std" so I had to add "include<iostream> to the header file and it seems to be fine now @fayrouz-mikhael

**Comment by fayrouz-mikhael** [comment]
Thank you @Gallald
